Заменил проверку Set'a слов на String
nekromant322/OverMoney pull request #100
Opened 2023-06-11 18:46 UTC by borisat

Заменил проверку Set'a слов на String.

2023-06-11 18:58 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
>      private Keyword getMatchingKeyword(Set<Category> categories, Set<String> words) {
сначала разбили сообщение на сет строк, потом снова собрали этот сет в строку
может лучше поменять сигнатуру методов? 
Category getMatchingCategory(_**String message**_, Set<String> keywords)
**_String_** getWords(String message)

2023-06-12 07:53 UTC, borisat commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
>      private Keyword getMatchingKeyword(Set<Category> categories, Set<String> words) {
Заменил сигнатуру  Set<String> getWords() на String getWords()

2023-06-12 08:11 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        String word = message.replaceAll("\\d+(\\.\\d+)?", "").trim();
Почему называется word, если по сути там много слов (еще и сам метод называется getWords)

2023-06-12 09:03 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        String word = message.replaceAll("\\d+(\\.\\d+)?", "").trim();
проблема вот в этом. не надо убирать символы из слов, подразумевается, что в строке message уже _**только**_ сообщение без суммы

например, трата на теле2 не пройдет корректно при такой реализации как сейчас

2023-06-12 09:06 UTC, VladimirBalakin requested changes
Не сработает корректно с ключевыми словами, содержащими цифры (теле2, 2берега, портвейн777)
Нужно убрать замену символов на ничто в словах

2023-06-12 16:38 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +                    break;
Пора наверное сказать, что тут нужна небольшая оптимизация и пометить внешний цикл примерно так
```
outer:
for (Category category : categories) {
...
    if (...) {
        ...
        break outer;
    }
}
```

В противном случае цикл продолжает выполнение для каждой категории.

2023-06-14 15:56 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        int lastSpaceIndex = message.lastIndexOf(" ");
магическую константу вынести и назвать ее соответствующе (SPACE)

2023-06-14 15:57 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        String words = String.join(" ", keywords);
ну тут та же магическая константа, что и в прошлом случае

2023-06-14 16:10 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        if (words.equals("")) {
я бы вернул isEmpty() или поменял местами аргументы на "".equals(words), иначе будут проблемы, если words равен null

2023-06-14 16:14 UTC, etozhealexis requested changes
порефакторить (магическая константа, методы `getMatchingCategory()` и `getMatchingKeyword()`)

2023-06-14 16:16 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        String words = String.join(" ", keywords);
я не понял эту строчку
если keywords теперь String, words будет равен строке, что сидит в keywords + пробел на конце? зачем?

2023-06-14 16:20 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        String words = message.substring(0, lastSpaceIndex).trim();
так сумма транзакции должна быть строго в конце, в какой-то момент от этого ушли, чтобы не помню что, порешали, что потом все равно будет анализатор сообщения прикручен, но от этого ограничения отказались, надо Толю докопать, как он видит это

2023-06-14 16:42 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        String words = message.substring(0, lastSpaceIndex).trim();
не понял сути и как оно сейчас работает  
но мне видится так: "пиво 11 22" это "пиво 11" с суммой 22

2023-06-15 14:31 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    private static final String SPACE = " ";
а зачем статик?

2023-06-15 14:42 UTC, nekromant322 commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/TransactionProcessingServiceTest.java
> +                Arguments.of("пиво теплое 123.45", "пиво теплое", 123.45f, null)
не вижу кейса в котором в категории была бы ключевая фраза, отписывал об этом выше

2023-06-15 16:09 UTC, borisat commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    private static final String SPACE = " ";
Я решил делать ее статик чтобы она не создавалась каждый раз. Переделал.

2023-06-15 16:18 UTC, borisat commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    private static final String SPACE = " ";
Чтобы не создавалась каждый раз. Переделал.

2023-06-15 16:29 UTC, nekromant322 approved these changes

2023-06-15 16:36 UTC, etozhealexis approved these changes

2023-06-15 18:29 UTC, VladimirBalakin approved these changes

2023-06-15 18:30 UTC, merged