Добавил автоматическое заполнение категорий у нераспознанных транзакций с одинаковым ключ.словом
nekromant322/OverMoney pull request #101
Opened 2023-06-11 19:23 UTC by NikitosikQQ

-Изменено заполненение TransactionQualifierDTO
-Изменена логика контроллера по /qualifier
-Добавлены методы в сервисы Keyword и Transaction для работы с одинаковыми нераспознанными транзакциям
-К новым методам добавлены unit тесты

2023-06-12 08:14 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/TransactionRepository.java
> +    @Modifying
почему через SQL запрос в репозитории, а не через save() в сервисе? 
как лучше?

2023-06-12 08:15 UTC, VladimirBalakin commented on dto/src/main/java/com/override/dto/TransactionQualifierDTO.java
> +    private String transactionComment;
зачем? две недели назад Толя мягко пнул сделать тип ЮИД у поля ДТО

2023-06-12 08:53 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/TransactionRepository.java
> +    @Query("UPDATE Transaction t SET t.category.id = :newCategory WHERE t.category.id is null AND t.message = :message")
SQL запрос обновляет транзакции, у которых (нет категории) и (одно и тоже сообщение) 
почему идентифицируешь транзакции в таблице транзакций, не упоминая account_id?

![image](https://github.com/nekromant322/OverMoney/assets/120746668/528e8a5d-efe0-4d3b-818f-55e4f7899094)

2023-06-12 08:55 UTC, VladimirBalakin requested changes
нам надо разобраться с: 
1) ДТО, я считаю, что его менять не следует
2) SQL запросом на обновление транзакции - я думаю, что он сработает некорректно, когда у разных аккаунтов нераспознанные транзакции с одним сообщением

2023-06-12 11:22 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/TransactionRepository.java
> +    @Modifying
Ну вроде как связь TransactionService -> TransactionRepository более очевидная да и каноны не нарушает, нежели TransactionService -> TransactionService -> TransactionRepository

2023-06-12 11:25 UTC, NikitosikQQ commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/KeywordServiceTest.java
> +import com.override.orchestrator_service.model.*;
Изменю

2023-06-12 11:27 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/QualifierController.java
> +            transactionService.setTransactionCategoryByMessage(transactionQualifierDTO.getTransactionComment(),
Таким образом сразу могут обновляться несколько транзакций с одинаковым ключевым словом. А по бизнес-логике, они должны быть уникальны в рамках одного аккаунта, поэтому вроде как я таким образом именно qualifier не ломаю

2023-06-12 11:27 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/TransactionRepository.java
> +    @Query("UPDATE Transaction t SET t.category.id = :newCategory WHERE t.category.id is null AND t.message = :message")
факт, исправлю

2023-06-12 13:06 UTC, nekromant322 commented on dto/src/main/java/com/override/dto/TransactionQualifierDTO.java
> +    private String transactionComment;
а нахера передавать с фронта на бэк примечание, если его прекрасно можно в бд достать по айди транзакции собственно?

2023-06-12 13:09 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +        transactionRepository.updateCategoryIdWhereCategoryIsNull(categoryId, transactionComment);
а зачем тут transactionComment?

2023-06-12 15:06 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/TransactionRepository.java
> +    @Modifying
"Нужно отослать на бэк айди транзакции и айди категории"
https://override-platform.atlassian.net/jira/software/c/projects/OV/boards/2?modal=detail&selectedIssue=OV-68

2023-06-12 16:29 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/QualifierController.java
> +                    transactionQualifierDTO.getCategoryId(), telegramUtils.getTelegramId(principal));
зачем телеграм ИД, если у нас ключевые слова и транзакции привязаны к внутреннему account_id, а не ИД пользователя в телеграме?

2023-06-12 16:32 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +    public void setTransactionCategory(UUID transactionId, Long categoryId, Long userId) throws InstanceNotFoundException {
зачем тут отдельно передавать userId, если accountId сидит и в транзакции и в категории?
![image](https://github.com/nekromant322/OverMoney/assets/120746668/19973f11-0949-400e-a1fe-716bacdc92c7)
![image](https://github.com/nekromant322/OverMoney/assets/120746668/3f2ca80a-6bd4-4cdf-a468-b84bb2fef52a)

2023-06-12 20:39 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
>      public void setTransactionCategory(UUID transactionId, Long categoryId) {
мне кажется лучше отдельный метод с говорящим названием типо СТАВИМ КАТЕГОРИЮ ДЛЯ ВСЕХ НЕРАСПОЗНАННЫХ ТРАНЗАКЦИЙ С ТАКИМ ЖЕ СООБЩЕНИЕМ

2023-06-12 20:41 UTC, nekromant322 requested changes
поменять название одного метода и закатывать

2023-06-13 10:40 UTC, nekromant322 approved these changes

2023-06-13 12:57 UTC, merged