Ov 115
nekromant322/OverMoney pull request #120
Opened 2023-06-20 12:05 UTC by borisat

Добавленa асинхронная запись подсказки

2023-06-20 12:14 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +
не вижу, чтоб использовал этих ребят

category service в category controller не очень 

и еще модификаторы доступа забыл

2023-06-20 12:14 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +
но первостепенно все таки то, что не используешь их

2023-06-20 12:16 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/feign/RecognizerFeign.java
> +                                                  @RequestParam UUID transactionId,
я бы заменил эти параметры на TransactionDTO

2023-06-20 12:18 UTC, etozhealexis commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +    OrchestratorFeign orchestratorFeign;
модификатор доступа

2023-06-20 12:20 UTC, etozhealexis commented on recognizer_service/src/main/java/com/override/recognizer_service/controller/rest/RecognizerController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
я хз зачем нативно тут посылать HttpStatus.OK, вроде с void при успешном выполнении и так ставится этот статус

2023-06-20 12:21 UTC, etozhealexis commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +        transactionDTO.setId(transactionId);
замени либо на билдер, либо на конструктор

2023-06-20 12:24 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        List<CategoryDTO> categories = categoryService.findCategoriesListByUserId(transactionMessageDTO.getChatId());
не правильный метод для нахождения транзакция

2023-06-20 14:31 UTC, etozhealexis submitted a review, later dismissed

2023-06-20 17:13 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +        transactionService.saveTransaction(transactionService.setSuggestedCategory(transactionDTO));
Раз предлагаемая категория назначается транзакции по ее сообщению, тут стоит назначать предлагаемую категорию не одной транзакции, а всем транзакциям одного аккаунта с одним сообщением.
Раз происходит возня с ворохом транзакций, лучше делать через запрос к бд на уровне репозитория, а не методами хибера.
посмотри, похожие запросы реализовали в TransactionRepository.

2023-06-20 17:19 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +    public Transaction setSuggestedCategory(TransactionDTO transactionDTO){
не нравится, что set метод что-то возвращает.  от него можно вообще отказаться, если это сеттер для поля класса? 

ты обновился до мастера после замены жадной загрузки на ленивую? есть ощущение, что своими нативными запросами к БД Никита уберег нас от проблем с типами загрузки.

2023-06-20 21:34 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +    public ResponseEntity<String> setSuggestedCategory(@RequestBody TransactionDTO transactionDTO) {
`setSuggestedCategory` что-то очень уж узкое, ендпоинт может быть использован в тысячах вариаций

2023-06-20 21:35 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +    public Transaction getTransactionWithSuggestedCategory(TransactionDTO transactionDTO) {
```suggestion
    public Transaction enrichTransactionWithSuggestedCategory(Long transaction Id, String suggestedCategory) {
```
getTransaction создает впечатление, что метод позволяет что-то достать

2023-06-20 21:37 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/feign/OrchestratorFeign.java
> +    ResponseEntity<String> setSuggestedCategory(@RequestBody TransactionDTO transactionDTO);
set не нравится в нейминге

2023-06-20 21:37 UTC, nekromant322 requested changes
стайл фиксы, а так все окс

2023-06-21 10:25 UTC, etozhealexis approved these changes

2023-06-21 10:52 UTC, nekromant322 approved these changes

2023-06-21 10:57 UTC, merged