Добавлено поле telegramUserID  в транзакции
nekromant322/OverMoney pull request #125
Opened 2023-06-21 18:08 UTC by borisat

Добавлено поле telegramUserID   в транзакцию и ДТО
Добавлен чейнджсет для обновления таблицы оркестратора

2023-06-21 18:25 UTC, etozhealexis commented on orchestrator_service/src/main/resources/db/changelog/v1.0.0/002-db.changelog-setTelegramUserIdInTransaction.xml
> +            <column name="telegram_user_id" type="BIGSERIAL">
bigserial?

2023-06-21 18:39 UTC, etozhealexis approved these changes

2023-06-21 20:46 UTC, nekromant322 requested changes
Нужен пруф

2023-06-21 20:46 UTC, nekromant322 commented on dto/src/main/java/com/override/dto/TransactionDTO.java
> +    private Long telegramUserId;
Зачем доьавлять, если не используем нигде?

2023-06-22 02:21 UTC, nekromant322 commented on dto/src/main/java/com/override/dto/TransactionDTO.java
> +    private Long telegramUserId;
я еще раз внимательно посмотрел и хоть убей не понимаю: сюда же айди никто не присылает

2023-06-22 15:21 UTC, etozhealexis approved these changes

2023-06-22 17:58 UTC, merged