[back] Удобнее двухстороннее распознавание транзакций
nekromant322/OverMoney pull request #128
Opened 2023-06-22 21:48 UTC by VladimirBalakin

Добавлена возможность писать транзакции с суммой траты в начале или в конце сообщения:
-Обновлена логика поиска суммы транзакции;
-Реализована возможность писать десятичную дробь с точкой и запятой в качестве разделителя;
-Добавлены тесты на обновленный функционал

2023-06-23 06:40 UTC, borisat approved these changes

2023-06-23 06:40 UTC, borisat commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        AMOUNT_IN_FRONT,
Возможно темка спорная, мне кажется, что луше б назвать "начало и конец"
```suggestion
        AMOUNT_AT_BEGINNING, 
        AMOUNT_AT_END,
        AMOUNT_AT_BEGINNING_RU_LOCALE,
        AMOUNT_AT_END_RU_LOCALE,
```  
или  

```suggestion
        BEGINNING_AMMOUNT, 
        END_AMMOUNT,
        BEGINNING_AMMOUNT_RU_LOCALE,
        END_AMMOUNT_RU_LOCALE,
```

2023-06-23 09:28 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    }
я возможно бы вынес в отдельный класс (но так тоже можно оставить), хезе

2023-06-23 09:31 UTC, etozhealexis commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/TransactionProcessingServiceTest.java
> +        );
200пиво 200 пиво
пиво 200 пиво200
200пиво 200 пиво200
(на всякий добавить)

2023-06-23 09:48 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    }
я думал в утиль или в какое-то общее для сервиса место записать, но тип транзакций, согласно модели - это другое, т.е. это чисто локальная штука
увидел, что остальные перечисления с константами у нас вообще в пакете дто лежат, что показалось очень странным.
так что это наверное пахнет микрозадачей - сделать отдельное место для перечислений

2023-06-23 09:49 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        AMOUNT_IN_FRONT,
я не англичанин, но посчитал, что так будет понятно
нужны еще мнения

2023-06-23 09:53 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        AMOUNT_IN_FRONT,
я за первый вариант Бориса

2023-06-23 10:48 UTC, VladimirBalakin commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/TransactionProcessingServiceTest.java
> +        );
добавил

2023-06-23 10:50 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    }
а вот регулярки, похоже, можно и в утиль

2023-06-23 16:10 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    }
"увидел, что остальные перечисления с константами у нас вообще в пакете дто лежат, что показалось очень странным." - если перечисления лежат в других классах, то класс дто их не видит, с Толей, когда обнаружили эту проблему, решили перенести их в дто, таким образом обошлись малой кровью

2023-06-24 14:00 UTC, etozhealexis approved these changes

2023-06-24 16:49 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        throw new InstanceNotFoundException("Invalid message");
А можно еще больше try-catch?

2023-06-24 16:50 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +                throw new InstanceNotFoundException("No keywords present in the message");
страный свич кейс, почему типов 4, а логик всего 2?

2023-06-24 16:51 UTC, nekromant322 submitted a review, later dismissed

2023-06-24 16:53 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    }
Я б в дто пихнул, хоть это не и не очень логично звучит  
а ваще хз почему аж отдельной задачей пахнет завести папки "contant"

2023-06-24 16:54 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    }
прям в оркестраторе и будут енамы лежать  
как будто бы не очень много делов)

2023-06-25 15:32 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        AMOUNT_IN_FRONT,
переименовал как в первом варианте предложил Борис

2023-06-25 15:33 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    }
енамов по всему проекту достаточно раскидано, перегнать все в отдельный пакет звучит как задача на онбординг, чтобы посмотреть структуру проекта, кмк

2023-06-25 15:36 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +        throw new InstanceNotFoundException("Invalid message");
а я не придумал по-другому
можно с ифами попробовать, но как будто так лучше видно логику

2023-06-25 15:44 UTC, borisat submitted a review, later dismissed

2023-06-25 15:53 UTC, etozhealexis approved these changes

2023-06-25 16:23 UTC, nekromant322 requested changes
Справится с исключениями, потому что перформанс такого решения около дна

2023-06-25 20:14 UTC, etozhealexis approved these changes

2023-06-26 10:59 UTC, nekromant322 approved these changes

2023-06-26 10:59 UTC, merged