Добавлено распознавание голосовых сообщений
nekromant322/OverMoney pull request #132
Opened 2023-06-23 17:08 UTC by etozhealexis

- удалена бд рекогнайзера (по договоренности с Толей)
- добавлено распознавание сообщений с помощью wit.ai
- добавлено распознавание числительных (wit.ai присылает цифры прописью, реализовал свой перевод прописи в цифры)
- почистил рекогнайзер (удалил ненужные зависимости и классы)

2023-06-23 17:33 UTC, NikitosikQQ commented on recognizer_service/src/main/java/com/override/recognizer_service/service/VoiceMessageService.java
> +    public String convertOggBytesToWavAndRecognizeText(byte[] voiceMessage) {
Я бы разделил эти 2 метода между собой, следуя S из solid, просто сделал бы какой-нибудь новый метод, аля getTextFromVoice, а там бы использовал методы convert и Recognize, мне кажется так лучше

2023-06-23 17:36 UTC, NikitosikQQ commented on recognizer_service/src/main/java/com/override/recognizer_service/service/voice/VoiceRecognitionServiceWitAI.java
> +    public String voiceToText(File wavFile) {
Так как Леха один вкурсе, что тут творится, может джавадок добавить, чтоб контекста побольше навалить?

2023-06-23 18:37 UTC, NikitosikQQ commented on recognizer_service/src/main/java/com/override/recognizer_service/service/VoiceMessageService.java
> +    public File convertOggBytesToWavAndRecognizeText(byte[] voiceMessage) {
Полагаю название должно быть без "AndRecognizeText"

2023-06-23 19:43 UTC, etozhealexis commented on recognizer_service/src/main/java/com/override/recognizer_service/service/VoiceMessageService.java
> +    public File convertOggBytesToWavAndRecognizeText(byte[] voiceMessage) {
Да, забыл убрать, поменяю

2023-06-24 16:35 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/VoiceMessageService.java
> +    public String convertOggBytesToWavAndRecognizeText(byte[] voiceMessage) {
поддерживаю господину

2023-06-24 16:36 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/VoiceMessageService.java
> +            throw new IOException("WAV voice file was not deleted");
в логах будет куча бесполезных записей без идентификаторов  
мб добавить айди юзера который прислал хотя бы?

2023-06-24 16:51 UTC, etozhealexis commented on recognizer_service/src/main/java/com/override/recognizer_service/service/VoiceMessageService.java
> +            throw new IOException("WAV voice file was not deleted");
ну это тогда либо в рекогнайзер засылать юзер ид, либо удалить отсюда логи и в логах бота сделать что-то по типу `user with id <id> sending voice`

2023-06-24 16:52 UTC, etozhealexis commented on recognizer_service/src/main/java/com/override/recognizer_service/service/VoiceMessageService.java
> +            throw new IOException("WAV voice file was not deleted");
либо и то и другое в целом

2023-06-24 21:34 UTC, nekromant322 commented on .github/workflows/build_and_deploy.yml
> +            echo WIT_AI_TOKEN = ${{ secrets.WIT_AI_TOKEN }} >> overmoney.txt
токен в сикреты закинул

2023-06-24 21:34 UTC, nekromant322 commented on recognizer_service/pom.xml
> +			<scope>compile</scope>
точно дважды надо?

2023-06-24 21:36 UTC, nekromant322 commented on recognizer_service/src/main/resources/application.yml
> +      version: 20230215
секретный урл и секретная версия?  
не очень понял такую иерархию пропертей

2023-06-24 21:38 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/WordsToNumbersService.java
> +    static {
chatGPT это, конечно хорошо  
но почему не @PostConstruct и наполнение нестатической HashMap?  
это ж дикий оверхед, а вдруг твой бин ваще не создадут (изза профиля или conditional какого-нибудь), а хешмапа набивается

2023-06-24 21:40 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/voice/VoiceRecognitionServiceWitAI.java
> +    public String voiceToText(File wavFile) {
Думаю дело не в доке  
Может лучше использовать православные RestTemplate или FeignClient?  
современный мир уже до них эволюционировал, но тут придется жоска вспотеть и без копипасты синтегрироваться

2023-06-24 21:44 UTC, nekromant322 requested changes
разобраться с иерархией пропетей, а так нормас  
Опциональная задача: эволюционировать в общении по http, а то реально нихера не понятно  
оставь хоть ссылку откуда копипастил  
а еще ссылку на доку апи можно над классом впаять

2023-06-25 13:23 UTC, nekromant322 approved these changes

2023-06-25 19:38 UTC, NikitosikQQ approved these changes

2023-06-25 19:40 UTC, merged

2023-06-25 19:47 UTC, VladimirBalakin approved these changes