Редактирование сохраненных транзакций
nekromant322/OverMoney pull request #153
Opened 2023-06-30 16:30 UTC by dementyD

- редактирование транзакций сохраненных (на странице "История")
- добавлено редактирование суммы транзакции 
- редактирование примечания (ключевое слово) при изменение ключевого слова - то которое было до редактирования, удаляется
- смена категорий (при смене категории - удаляется ключевое слово только данной транзакции(если оно было))
- при клике на строку в таблице транзакций - открывается модальное окно для редактирования 
- ссылки в нав меню теперь на рф языке

2023-06-30 19:32 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +    }
/edit лишнее  
см https://habr.com/ru/articles/351890

2023-06-30 19:40 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    Keyword findKeywordByKeywordIdName(String name);
Optional<Keyword>

2023-06-30 19:41 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    Keyword findKeywordByKeywordIdName(String name);
```suggestion
    Optional<Keyword>findKeywordByKeywordIdName(String name);
```

2023-06-30 19:41 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +        }
тогда тут проверка будет красивше

2023-06-30 19:42 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    void deleteByKeywordIdName(String name);
не очень понятно что делает метод, почему параметр name?

2023-06-30 19:44 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +        return transactionUpdate;
```suggestion
        return transactionRepository.save(transactionUpdate);
```

2023-06-30 19:44 UTC, nekromant322 requested changes
мелкие правки по стайлу

2023-06-30 22:05 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/CategoryRepository.java
> +    Category findByName(String name);
Надо взять в расчет еще и id аккаунта, так как категорий "Продукты" в базе будет дохера

2023-06-30 22:07 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    Keyword findKeywordByKeywordIdName(String name);
А если у разных аккаунов keywordName совпадет? Думаю тут тоже стоит по accId еще проверять. А лучше сразу по всему keywordId(там и name и accId лежит)

2023-06-30 22:07 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    void deleteByKeywordIdName(String name);
Тут он вообще всем аккаунтам удалит похожие ключевые слова, надо акк тоже проверять

2023-07-03 16:24 UTC, dementyD commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +        }
немного переделал логику... и сейчас не могу что то въехать как Optional сделает красивее код проверки на null

2023-07-03 16:27 UTC, dementyD commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    void deleteByKeywordIdName(String name);
после коментов Никиты переделал метод - теперь он ищет Keyword по аккаунт ID и по name у KeywordId

2023-07-03 22:15 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    Keyword findKeywordByKeywordIdNameAndAccountId(@Param("id") Long id, @Param("name") String name);
По сути keywordId и есть name + accId. может передать сюда сразу keywordId и заменить на findKeywordByKeywordId? да

2023-07-03 22:17 UTC, NikitosikQQ commented on orchestrator_service/src/main/resources/static/scripts/history_scripts.js
> +            url: "/transactions",
вроде как тут лучше вначале добавить точку, чтобы путь был относительным

2023-07-04 16:38 UTC, closed without merging