Отправка багрепорта
nekromant322/OverMoney pull request #175
Opened 2023-07-12 13:33 UTC by borisat

- Добавлена отправка баг репорта со страницы /settings
- Добавлена сущность и дто
- Добавлена БД
- Добавлены тесты

2023-07-12 14:47 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/SettingsController.java
> +    }
выглядит как отдельный контроллер  
сущность то совершенно самостоятельная  
а то что живет в настройках - так это для удобства

2023-07-12 14:48 UTC, nekromant322 requested changes
нужен рефакторинг

2023-07-12 15:01 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/model/BugReport.java
> +
```suggestion

@NotNull 
```

2023-07-12 15:04 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/mapper/BugReportMapper.java
> +        return BugReport.builder()
```suggestion
        return new BugReport(bugReportDTO.getId(), 
            bugReportDTO.getReport(),
            ....)
```

2023-07-12 15:07 UTC, VladimirBalakin commented on orchestrator_service/src/main/resources/db/changelog/v1.0.0/006-db.changelog-createBugReportTable.xml
> +            <column name="report" type="VARCHAR(255)">
может UUID? число багрепортов публичным делать странно кмк

2023-07-12 15:10 UTC, VladimirBalakin commented
мне кажется странным использовать билдер на сущности, у которой требуются ненулевые поля.
при этом про ненулевые поля узнаешь только в ликвибэйзе, я бы отразил это в модели. 
как будто это все запутывает

2023-07-13 11:08 UTC, nekromant322 approved these changes

2023-07-13 11:28 UTC, IseMonogatari approved these changes

2023-07-13 11:29 UTC, merged