Новый секурити фильтр
nekromant322/OverMoney pull request #183
Opened 2023-07-17 14:30 UTC by borisat

-Добавлен новый фильтр(проверяет кастомный хедер)
-Обновлен филтр чейн в секуритиКонфиг
-Добавлен конфиг фейна и кастомный хедер в ТГбот и Рекогнайзер
-Добавлены переменные в ямлы

2023-07-17 19:37 UTC, nekromant322 requested changes
Скажи мне как назвать сикретик, положу туда секретную лабуду и погнали  
жду правок по подтягиванию сикрета из енвов

2023-07-18 17:06 UTC, nekromant322 commented on docker-compose.dev.yaml
> +      INTERNAL_KEY_HEADER: X-INTERNAL-KEY
эмм [2]  
строчка выше не намекает?

2023-07-18 17:07 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/config/filter/InternalKeyAuthenticationFilter.java
> +    private List<String> allowedURIList;
если будешь еще ПР править - сделать configuration Properties и вынеси в отдельный класс

2023-07-19 08:01 UTC, IseMonogatari approved these changes

2023-07-19 10:16 UTC, merged