Добавлена возможность загрузки транзакций из Exel
nekromant322/OverMoney pull request #190
Opened 2023-07-18 18:27 UTC by EduardCoool

2023-07-19 17:28 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionFromExelController.java
> +    TelegramUtils telegramUtils;
private

2023-07-19 17:34 UTC, EduardCoool commented on orchestrator_service/src/main/java/com/override/orchestrator_service/model/Category.java
> +    }
На правильной работе  equals завязаны многие методы 
например в этом месте:  categories.removeAll(overMoneyAccount.getCategories());
также это позволяет использовать Set<Category> тем самым мы себя обезопасим от ошибки в бд

2023-07-19 18:17 UTC, IseMonogatari commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionFromExelController.java
> +    @GetMapping("/loading/transactions")
А может стоит сделать url как @RequestionMapping("/loading/transactions") над контроллером? А то вдруг этот контроллер будет разрастаться и прочее..

2023-07-19 22:00 UTC, EduardCoool commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionFromExelController.java
> +    @GetMapping("/loading/transactions")
не думаю что на данном этапе это требуется

2023-07-20 16:11 UTC, dementyD commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    public Category getMatchingCategory(Set<Category> categories, String words) {
private на public норм практика махнуть? я тоже воспользовался данной фишкой - подсмотрев у тебя(и методом тоже - вообще есть сомнения что этому методу тут место в "TransactionProcessingService" раз он нужен уже в трех классах мб его в CategoryService публичным) уточню на дейлике - как в таких ситуациях быть

2023-07-20 16:31 UTC, EduardCoool commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionProcessingService.java
> +    public Category getMatchingCategory(Set<Category> categories, String words) {
хорошее замечание, думаю махнуть точно можно, а вот про перенос в категорию - возможно

2023-07-20 21:01 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionFromExelController.java
> +public class TransactionFromExelController {
Не, мне нравится, как раз специфичная очень задача, которая отдельно от остального бизнеса 
по сути костыль, чтоб я перенес свои транзакции из мобса

2023-07-20 21:03 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionExelService.java
> +public class TransactionExelService {
во-первых Excel  
во-вторых вероятно лучше будет XLSX везде вместо Exel, потому что мы не с проприетарным софтом собираемся работать, а с форматом файлов

2023-07-20 21:05 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionExelService.java
> +        workbook.close();
close() может не вызваться, если вдруг эксепшон при парсинге данных произойдет  
олосо тут тысяча и одна ошибка может случится, думаю стоит try () catch() { прокинуть свое исключение аля XlsxProcessingException }

2023-07-20 21:07 UTC, nekromant322 requested changes
Наворотить обработку ошибок при парсинге xlsx + фикс нейминга

2023-07-24 22:15 UTC, nekromant322 approved these changes

2023-07-25 09:43 UTC, borisat commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionXLSXService.java
> +                .type(Type.EXPENSE)
А почему тип Expense? там не может быть доходных категорий в файле?

2023-07-25 10:20 UTC, EduardCoool commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionXLSXService.java
> +                .type(Type.EXPENSE)
при добавлении категорий к этим транзакций сразу заношу их  как расходы, тк из эксель файла не представляется возможным узнать доходы это или расходы, да и в тестовых файлах не было доходных транзакций и по ТЗ не обговаривалось

2023-07-25 10:21 UTC, borisat approved these changes

2023-07-25 11:16 UTC, merged