настроен максимальный размер загружаемого нам файла или запроса
nekromant322/OverMoney pull request #232
Opened 2023-07-31 13:03 UTC by dementyD

- Добавлен конфиг с настройками max размера файла или запроса
- Теперь к нам не поступит запрос или файл более 10мб

p.s На фронте уведомление не получилось протестить... тк как через нгрок грузит любые файлы ..а постман форнт не показывает(но вроде должно уведомление отрабатывать)

2023-07-31 13:17 UTC, nekromant322 requested changes
Я бы вынес в конфиги

2023-07-31 13:17 UTC, IseMonogatari submitted a review, later dismissed

2023-08-02 13:31 UTC, IseMonogatari submitted a review, later dismissed

2023-08-02 14:06 UTC, nekromant322 commented on orchestrator_service/src/main/resources/application.yml
> +      max-size: '10MB'
А зачем отдельную заводить, если можно в ошибке вернуть ту что ниже в ямлике???

2023-08-02 17:59 UTC, nekromant322 approved these changes

2023-08-03 08:03 UTC, merged