Улучшен алгоритм распознавания голосовых транзакций
nekromant322/OverMoney pull request #236
Opened 2023-08-02 18:20 UTC by EduardCoool

* Теперь доступно голосовое распознавание транзакций по типу: Пиво 200 рублей
* Исправлен баг при котором к словам подставлялась точка изи запятая в конце, что мешало распознаванию транзакций

2023-08-02 19:23 UTC, IseMonogatari submitted a review, later dismissed

2023-08-02 19:59 UTC, nekromant322 approved these changes

2023-08-02 19:59 UTC, nekromant322 requested changes
Юнит тестов бы

2023-08-02 20:16 UTC, borisat submitted a review, later dismissed

2023-08-03 14:12 UTC, IseMonogatari approved these changes

2023-08-03 14:48 UTC, nekromant322 approved these changes

2023-08-03 14:57 UTC, merged