Отрисовка новых транзакций на overview без обновления страницы
nekromant322/OverMoney pull request #237
Opened 2023-08-03 20:53 UTC by IseMonogatari

Добавлено:

- Отрисовка производится с помощью long polling`а.
- Настройка 'величины активности' и времени long polling`а определяется через .yaml

2023-08-03 20:59 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +    }
что это за костыль -_-

2023-08-03 21:00 UTC, nekromant322 requested changes
Не понял назначение getLongPollingList  
можно внедри пропсы если вдруг где-то надо же
вроде

2023-08-04 16:46 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +    }
точно не тут! этот функционал никак не связан с ресурсом transaction  
можно унести куда-то в отдельное место где всякая мета инфа будет  
из подобного - ендпоинт для получения имени тг бота

2023-08-04 16:46 UTC, nekromant322 requested changes
Не трогать ендпоинт транзакций

2023-08-04 21:17 UTC, nekromant322 approved these changes

2023-08-04 21:33 UTC, borisat approved these changes

2023-08-04 22:40 UTC, merged