Добавлена миграция в бд для таблицы telegram_message
nekromant322/OverMoney pull request #238
Opened 2023-08-04 15:23 UTC by EduardCoool

* Добавлена миграция в бд для таблицы telegram_message

2023-08-04 16:00 UTC, IseMonogatari submitted a review, later dismissed

2023-08-04 16:01 UTC, dementyD submitted a review, later dismissed

2023-08-04 16:48 UTC, nekromant322 commented on telegram_bot_service/src/main/resources/db/changelog/v1.0.0/003-db.changelog-createTableTelegramMessage.xml
> +            <column name="id" type="SERIAL">
SERIAL?  
а разве тут не айди сообщения будет?

2023-08-04 19:39 UTC, IseMonogatari submitted a review, later dismissed

2023-08-04 20:13 UTC, dementyD commented on telegram_bot_service/src/main/resources/db/changelog/v1.0.0/003-db.changelog-createTableTelegramMessage.xml
> +            <column name="id" type="INTEGER">
INTEGER или BIGINT вот в чем вопрос -_- ?

2023-08-04 20:23 UTC, EduardCoool commented on telegram_bot_service/src/main/resources/db/changelog/v1.0.0/003-db.changelog-createTableTelegramMessage.xml
> +            <column name="id" type="INTEGER">
INTEGER тк id имеет тип Integer у тип BIGINT имеет больший диапозон, это уже для Long

2023-08-04 20:31 UTC, dementyD submitted a review, later dismissed

2023-08-04 21:34 UTC, nekromant322 commented on telegram_bot_service/src/main/resources/db/changelog/v1.0.0/003-db.changelog-createTableTelegramMessage.xml
> +            <column name="id" type="INTEGER">
Есть мнение, что сообщения в разных диалогах могут иметь один и тот же айди. Стоит это обмозговать и сделать фикс :) дементию спасибо за мысль

2023-08-04 21:35 UTC, nekromant322 requested changes
Решить вопрос с PK для мессадж айди

2023-08-07 15:15 UTC, nekromant322 approved these changes
Выкатывая - наебнешь, даю тысячу процентов  
приготовься зачинить руками на тесте

2023-08-07 15:18 UTC, dementyD approved these changes

2023-08-08 14:25 UTC, merged