Сохранение user_id Telegram API в бд оркестратора
nekromant322/OverMoney pull request #24
Opened 2023-04-29 13:10 UTC by kyomexd

ID юзера в базе данных теперь идентично user_id из Telegram API

При авторизации проверяется наличие ID в бд (вместо юзернейма, который может быть изменен пользователем)

2023-04-29 13:42 UTC, etozhealexis reviewed
c кайфос

2023-05-02 19:52 UTC, nekromant322 requested changes

2023-05-02 19:52 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/UserService.java
> +        return userRepository.findById(id).orElse(null);
а null точно лучше?

2023-05-02 21:19 UTC, etozhealexis reviewed
см

2023-05-03 00:02 UTC, nekromant322 approved these changes

2023-05-03 11:35 UTC, merged