Update метода saveAllCategoriesFromXLSX
nekromant322/OverMoney pull request #242
Opened 2023-08-06 11:38 UTC by EduardCoool

* Сравнение категорий происходит по имени, непосредственно в методе
* При отсутствии категорий у пользователя, добавляются дефолтные категории

2023-08-06 12:16 UTC, nekromant322 requested changes
Пересмотреть подход к ошибкам

2023-08-06 12:16 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionFromXLSXController.java
> +    public ResponseEntity<String> loadingTransactionsFromXLSX(Principal principal, @RequestPart("data") MultipartFile file) throws InstanceNotFoundException {
Зачем тут такое счастье? Почему не обернуть в наш кастомный эксепшон

2023-08-06 12:16 UTC, nekromant322 commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/TransactionXLSXServiceTest.java
> +import javax.management.InstanceNotFoundException;
Чет туфта какая-то, так и не понял зачем оно нам надо

2023-08-06 12:17 UTC, nekromant322 commented
А, зачем дефолтные добавлять в этой фиче, если из файлика загружаем транзакции и создаем категории??

2023-08-06 12:21 UTC, EduardCoool commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/TransactionXLSXServiceTest.java
> +import javax.management.InstanceNotFoundException;
это метод setDefaultCategoryForAccount передаёт

2023-08-07 11:22 UTC, IseMonogatari approved these changes

2023-08-07 11:23 UTC, merged