moex api intagration
nekromant322/OverMoney pull request #301
Opened 2024-04-14 19:55 UTC by NollReferenceException

2024-04-15 16:37 UTC, nekromant322 commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +    private final String IMOEX_JSON_STRING_URL = "https://siss.moex.com/iss/statistics/engines/stock/markets/index/analytics/imoex.json?limit=100";
стоит унести в .yml для удобство конфигурации в будущем

2024-04-15 16:38 UTC, nekromant322 commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
Философия спринга в избавлении от `new` :)

2024-04-15 16:39 UTC, nekromant322 commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +                objectWriter.writeValue(new File(IMOEX_DATA_FILENAME), jsonNode);
Зачем файл, если можно сразу прочитать в хешмапу?  
ну или например в лист  и его потом в мапу переложить  
Предлагаю замутить MOEXFeignClient и не писать эту кучу лишнего сложного кода

2024-04-15 16:40 UTC, nekromant322 requested changes
Переделать по замечаниям

2024-04-16 06:07 UTC, NollReferenceException commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +                objectWriter.writeValue(new File(IMOEX_DATA_FILENAME), jsonNode);
> Зачем файл, если можно сразу прочитать в хешмапу? ну или например в лист и его потом в мапу переложить Предлагаю замутить MOEXFeignClient и не писать эту кучу лишнего сложного кода

файл сохраняю чтобы каждый раз через интернет не обращаться к API и на случай если API будет недоступно, какое-то время можно будет брать данные из файла пока API не починят

2024-04-16 18:49 UTC, etozhealexis commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +            for (JsonNode jn : jsonNode.get("analytics").get("data")) {
тут как будто бы тоже

2024-04-16 18:51 UTC, etozhealexis commented on invest_service/src/main/resources/application.yml
> +    index-url-data: https://iss.moex.com/iss/statistics/engines/stock/markets/index/analytics
может лучше вынести в переменную окружения?
(и поставить по дефолту эту ссылку)

2024-04-16 19:09 UTC, NollReferenceException commented on invest_service/src/main/resources/application.yml
> +    index-url-data: https://iss.moex.com/iss/statistics/engines/stock/markets/index/analytics
тут получается что это ссылка константная и как-будто нет смысла в переменную среды выносить

2024-04-16 19:10 UTC, NollReferenceException commented on invest_service/src/main/resources/application.yml
> +    index-url-data: https://iss.moex.com/iss/statistics/engines/stock/markets/index/analytics
> может лучше вынести в переменную окружения? (и поставить по дефолту эту ссылку)

тут получается что это ссылка константная и как-будто нет смысла в переменную среды выносить

2024-04-16 19:10 UTC, NollReferenceException commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +            for (JsonNode jn : jsonNode.get("analytics").get("data")) {
> тут как будто бы тоже

согласен, хуйню сделал

2024-04-16 19:11 UTC, NollReferenceException commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +                ResponseEntity<JsonNode> response = MOEXFeignClient.getIndexIMOEX(100);
> магическая константа

согласен, хуйню сделал

2024-04-16 20:15 UTC, SemionHaritonov commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +            throw new RuntimeException(e);
в чем смысл перехватывать IOE и передавать дальше RTE?

2024-04-16 20:25 UTC, SemionHaritonov commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +        return jsonNode;
я бы обернул в Optional, раз потенциально может вернутся нуль.

2024-04-17 09:43 UTC, NollReferenceException commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +        return jsonNode;
он никогда не сможет вернуть null, эксепшн выпадет раньше, но согласен, возможно стоить по другому переписать код

2024-04-17 09:44 UTC, NollReferenceException commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +        return jsonNode;
> я бы обернул в Optional, раз потенциально может вернутся нуль.

он никогда не сможет вернуть null, эксепшн выпадет раньше, но согласен, возможно стоить по другому переписать ко

2024-04-17 22:56 UTC, nekromant322 commented on invest_service/src/main/resources/application.yml
> +    index-url-data: https://iss.moex.com/iss/statistics/engines/stock/markets/index/analytics
плюсую, смысла нет никакого ее скрывать и отсюда уносить  
даже если надо будет поменять - тут будет проще

2024-04-17 22:57 UTC, nekromant322 commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +            throw new RuntimeException(e);
я бы подумал на фолбэк механикой  
Сейчас тут полностью завязываешь функционал сервиса на этой интеграции  
Я бы имел под рукой какие-то дефолтные значения все таки на случай недоступности апи

2024-04-17 22:58 UTC, nekromant322 commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +            for (JsonNode jn : jsonNode.get("analytics").get("data")) {
ДТО класс - хорошее решение, будет понятно описывать структуру ответа, если надо будет еще че-то дернуть оттуда - класс проще развивать чем это процедурное детище

2024-04-18 08:11 UTC, NollReferenceException commented on invest_service/src/main/java/com/override/invest_service/service/MOEXService.java
> +            throw new RuntimeException(e);
> я бы подумал на фолбэк механикой Сейчас тут полностью завязываешь функционал сервиса на этой интеграции Я бы имел под рукой какие-то дефолтные значения все таки на случай недоступности апи

не знаю хорошая ли практика, но можно просто файлик с данными в гит репу запушить

2024-04-18 20:09 UTC, nekromant322 requested changes
- добавить фолбэк механику
- подготовить почву под отображение даты для которой расчитан индекс
- специфичное ДТО снести внутрь инвеста

2024-04-20 22:14 UTC, nekromant322 approved these changes

2024-04-22 09:02 UTC, merged