Добавил больше статистики для администраторов
nekromant322/OverMoney pull request #326
Opened 2024-06-30 21:21 UTC by EvgeniyKulpinov

Обновил список администраторов
Добавил информацию:
- количество активных аккаунтов за последний месяц
- количество транзакций в последний месяц и в последний полный день
- среднее количество транзакций в день по всем пользователям за последний месяц

2024-06-30 22:02 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/OverMoneyAccountService.java
> +        Iterable<OverMoneyAccount> accounts = overMoneyAccountRepository.findAll();
Легчайшая OOM, надо бы в базе посчитать

2024-06-30 22:03 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/AccountController.java
> +    @GetMapping("/activeAccountCount")
Предлагаю не мусорить в апи транзакций и сделать админские штучки в отдельном месте

2024-07-01 01:05 UTC, EvgeniyKulpinov commented
Всё поправил

2024-07-01 02:52 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/OverMoneyAccountRepository.java
> +    @Query("SELECT COUNT(DISTINCT a.id) FROM OverMoneyAccount a WHERE a.id IN (SELECT t.account.id FROM Transaction t WHERE t.date >= :date)")
можно еще один дистинкт кажется добавить для оптимизации

2024-07-01 02:53 UTC, nekromant322 requested changes
Еще немного оптимизации и можно закатывать

2024-07-01 13:14 UTC, EvgeniyKulpinov commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/OverMoneyAccountRepository.java
> +    @Query("SELECT COUNT(DISTINCT a.id) FROM OverMoneyAccount a WHERE a.id IN (SELECT t.account.id FROM Transaction t WHERE t.date >= :date)")
поправил

2024-07-01 16:42 UTC, nekromant322 approved these changes

2024-07-01 17:54 UTC, merged