Добавлен Swagger
nekromant322/OverMoney pull request #334
Opened 2024-07-07 12:11 UTC by p1peCode

Добавлен Swagger доступный по /swagger-ui.html для списка админов, расставлены основные аннотации в контроллерах с категориями и  транзакциями

2024-07-07 17:14 UTC, SemionHaritonov commented on orchestrator_service/src/main/java/com/override/orchestrator_service/config/SecurityConfig.java
> +    private String[] allowedUsers;
почему массив, а не коллекция?

2024-07-07 17:17 UTC, SemionHaritonov commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/CategoryController.java
> +@Tag(name = "Контроллер категорий", description = "Операции относящиеся к категориям")
```suggestion
@Tag(name = "Контроллер категорий", description = "Операции, относящиеся к категориям")
```

2024-07-07 17:20 UTC, SemionHaritonov commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +                                                       @Parameter(description = "Размер страницы") @RequestParam(defaultValue = "50") Integer pageSize,
```suggestion
                                                       @Parameter(description = "Транзакций на странице") @RequestParam(defaultValue = "50") Integer pageSize,
```

размер страницы не понятно что такое

2024-07-07 17:23 UTC, SemionHaritonov commented
у многих методов возможен выброс исключения. надо бы прописать, какие коды возможно получить при отправке запроса на эндпоинт.

2024-07-07 18:23 UTC, SemionHaritonov commented
у нас только 404 возможно? 
а в случае успешного выполнения возвращается всегда 200? или есть какие-то варианты? 
еще на успех аналогично ошибке надо добавить комментарии, чтоб документация была полная

2024-07-07 23:33 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/CategoryController.java
> +@Tag(name = "Контроллер категорий", description = "Операции относящиеся к категориям")
На уровне апи не существует понятия контроллер, абстркция протекла

2024-07-07 23:35 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/CategoryController.java
> +@Tag(name = "Контроллер категорий", description = "Операции относящиеся к категориям")
лучше уж тогда просто "Операции с категориями"

2024-07-07 23:37 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/config/SecurityConfig.java
> +                .access("hasAnyAuthority(" + String.join(",", allowedUsers) + ")")
а это точно так работает? что-то выглядит сомнительно  
В проекте аж целый фильтр изобретен, чтоб доступ админам выдавать, см AdminPageFilter

2024-07-07 23:39 UTC, nekromant322 requested changes
Смазать анноташками с докой дтошки которые в запросах и ответах документируемых апи

2024-07-08 16:43 UTC, nekromant322 commented on dto/src/main/java/com/override/dto/MergeCategoryDTO.java
>       */
эту доку можно в свагеровскую перенести и выпилить

2024-07-08 16:43 UTC, nekromant322 commented on dto/src/main/java/com/override/dto/MergeCategoryDTO.java
>       */
аналогично

2024-07-08 16:43 UTC, nekromant322 approved these changes
чуть доку подправить и ехало

2024-07-08 17:42 UTC, nekromant322 approved these changes

2024-07-08 17:50 UTC, Elminst3r1988 approved these changes

2024-07-08 17:51 UTC, merged

2024-07-08 17:55 UTC, CoolCat100 approved these changes