Добавлена команда "анонс" в бота
nekromant322/OverMoney pull request #335
Opened 2024-07-07 21:29 UTC by CoolCat100

Добавлена команда "анонс" в бота

2024-07-07 22:00 UTC, SemionHaritonov commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/commands/AnnounceCommand.java
> +                log.info("pusto");
gryazno

2024-07-07 22:01 UTC, SemionHaritonov commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/commands/AnnounceCommand.java
> +                log.info("pochta " + mailsInPending.get(i));
gryazno

2024-07-07 22:01 UTC, SemionHaritonov commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/commands/AnnounceCommand.java
> +                log.info("Готовим почту");
тут и ранее стоит вынести константы

2024-07-07 23:40 UTC, nekromant322 commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/constants/Command.java
> +    ANNOUNCE("announce", "Отправить аннонс о новых возможностях указанным пользователям");
только указанным?)

2024-07-07 23:42 UTC, nekromant322 commented on telegram_bot_service/src/main/resources/application.yml
> +      Denis_Shvartcer
плохо в два места дублировать
проще ендпоинт в оркестраторе для таких нужд небольшой сделать и из него дернуть  
можно еще @OnlyServiceUse на него повесить

2024-07-07 23:44 UTC, nekromant322 commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/commands/OverMoneyCommand.java
> +}
копипаста с ревью бота, конечно здоровская, но как будто тут смысла особо не имеет  
и почему sendMessage оказался в этой абстракции а не контретно в AnnounceCommand?

2024-07-07 23:45 UTC, nekromant322 commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/commands/OverMoneyCommand.java
> +}
я б избавился от такого счастья  
а еще такую большую кучу логов на каждый простой чих писал бы в debug

2024-07-07 23:50 UTC, nekromant322 requested changes
отработать по комментам
раз такая пьянка пошла - можно и другие команды в классы вынести, ждем в следующем ПР - как с этим закончим

2024-07-08 09:03 UTC, CoolCat100 commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/commands/AnnounceCommand.java
> +                log.info("pusto");
ахаха, я забыл удалить временные логи, искал ошибку и навставлял

2024-07-08 16:41 UTC, nekromant322 approved these changes

2024-07-08 17:31 UTC, EvgeniyKulpinov approved these changes

2024-07-08 17:33 UTC, merged