Добавлена функция фильтрации в историю транзакций(Теперь не из форка)
nekromant322/OverMoney pull request #341
Opened 2024-07-10 22:10 UTC by EvgeniyKulpinov

Добавлена функция фильтрации в историю транзакций, которая позволяет использовать JSON с параметрами для настройки фильтров

2024-07-11 05:06 UTC, Elminst3r1988 commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/TransactionServiceTest.java
> +    }
Сейчас в тесте генерируются 2 одинаковых транзакции, и в независимости от фильтров всегда возвращаются обе. Может быть сделать вручную 2 транзакции с разными полями, где по результатам применения фильтров будет возвращаться сначала одна, потом другая, потом обе?

2024-07-11 10:03 UTC, NollReferenceException requested changes

2024-07-11 19:02 UTC, EvgeniyKulpinov commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +    public List<TransactionDTO> findTransactionsByUserIdLimitedAndFiltered(Long id, TransactionFilter filter) throws InstanceNotFoundException {
Эксепшн формируется с сообщением в юзер сервисе и прокидывается на самый верх.
По валидации я пока не знаю будет ли у пользователей возможность ввести не корректные данные, фронта пока нет.
Всё сделал по аналогии с остальными методами в контроллере и сервисе

2024-07-12 23:07 UTC, EvgeniyKulpinov commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/TransactionSpecificationTest.java
> +        assertThat(specification).isNotNull();
на что ещё тут можно проверять я не придумал,  тут только поправил косяк с resultPredicate, проверяю что он тоже создается

2024-07-13 00:04 UTC, EvgeniyKulpinov commented
Внес правки в тесты

2024-07-14 12:00 UTC, nekromant322 approved these changes

2024-07-14 13:40 UTC, CoolCat100 approved these changes

2024-07-14 13:42 UTC, merged