улучшена функция подсказки, установлен минимальный порог точности-0.7…
nekromant322/OverMoney pull request #398
Opened 2024-09-06 19:20 UTC by annov4

…, при котором подсказка по категориям срабатывает

2024-09-06 23:01 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +    private float minAccuracy;
а почему тут минимальная точность используется?
как будто логичнее на мой вкус любой ответ слать в оркестратор, там на месте уже решить показывать пользователю или нет (использовать suggestedCategoryId и сохранить его в базу или нет)

2024-09-06 23:04 UTC, nekromant322 requested changes
Так-то в целом ок, только логику в оркестратор перетащить
из задачи:

_Хранить_ в бд оркестраторе не только айди подсказанной категории, но и точность подсказки

В оркестраторе добавить в .yml настройку минимальной точности при которой подсказка будет учитываться и реализовать это в коде (не возвращать с апи подсказку на фронт, если она хреновая)

2024-09-09 19:46 UTC, mabalda commented on orchestrator_service/src/main/resources/db/changelog/v1.0.0/017-db.changelog-add-accuracyTooltip_column.xml
> +  <changeSet author="annov4" id="23.07.2024-addLastUsedColumn">
поменяй айдишник ченжсета, старый подтянула

2024-09-09 19:52 UTC, mabalda commented on recognizer_service/src/test/java/com/override/recognizer_service/service/CategoryRecognizerServiceTests.java
> +        Assertions.assertNull(recognizedCategory == null ? null : (accuracy < minAccuracy ? null : recognizedCategory));
я бы отделила пробелами части с вводными данными, вызовом тестируемого метода и ассертом. как полагается по given/when/then

2024-09-09 19:53 UTC, mabalda commented on recognizer_service/src/test/java/com/override/recognizer_service/service/CategoryRecognizerServiceTests.java
> +    public void setup() {
перетащи метод под моки, чтобы был порядок

2024-09-10 13:40 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/TransactionService.java
> +        transactionRepository.save(transaction);
сохраняем точность, но при этом не сохраняем для чего она, если она маленькая? 
просто бесхозная цифра будет висеть?)

2024-09-11 00:07 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/mapper/TransactionMapper.java
>                  .suggestedCategoryId(transaction.getSuggestedCategoryId())
А может тут просто не будем проставлять подсказку в дто если точность маленькая? Да и фронту вроде сама точность нафиг не уперлась. 
Это на каждом фронте надо будет мин точность не забыть проставить, проще не отдавать с бэка

2024-09-11 15:48 UTC, nekromant322 approved these changes

2024-09-11 17:33 UTC, merged