OV280 New Endpoint
nekromant322/OverMoney pull request #400
Opened 2024-09-07 18:47 UTC by AlxndrKatz

Новый эндпойнт "/analytics/v2/delta" для отображения сравнения данных текущего месяца с предыдущим и одноименным месяцем прошлого года (если есть данные за эти периоды).

2024-09-07 21:57 UTC, nekromant322 commented on dto/src/main/java/com/override/dto/AnalyticsDataMonthDiffDTO.java
> +}
добавить свагер доку

2024-09-07 21:57 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/AnalyticsV2Controller.java
> +        return analyticV2Service.getMonthDiff(telegramUtils.getTelegramId(principal));
добавить свагер доку

2024-09-07 21:59 UTC, nekromant322 requested changes
Так-то все нравится, только доку добавить и можно закатывать

2024-09-08 15:35 UTC, AlxndrKatz commented
Аннотировал для Сваггер-документации упомянутые классы

2024-09-08 20:10 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/AnalyticsV2Controller.java
> +            @ApiResponse(responseCode = "404", description = "Данные не найдены"),
а эти коды реально возращаются? чет не видел обработчиков

2024-09-08 20:11 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/AnalyticV2Service.java
> +    public AnalyticsDataMonthDiffDTO getMonthDiff(Long overMoneyAccountId) {
мб разбить на методы? жирный метод получается, в нем считается вообще все  
мб даже на классы?

2024-09-08 20:14 UTC, nekromant322 commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/AnalyticV2ServiceTest.java
> +        int previousMonth = currentMonth - 1;
добавить тест на случай отсутствия инфы по прошлым месяцам или годам (выглядит как два теста, надо проверить что там null будет по итогу)

2024-09-08 20:14 UTC, AlxndrKatz commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/AnalyticsV2Controller.java
> +            @ApiResponse(responseCode = "404", description = "Данные не найдены"),
Верно, возврат 400 и 404 не предусмотрен. Сейчас копипасту приберу.

2024-09-08 20:17 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/AnalyticV2Service.java
> +                .findSumTransactionsPerSpecificMonthForAccount(overMoneyAccountId, previousYear, currentMonth);
Новерин предлагает не блочится 4 раза на запросы в базу, а сделать их асинхронными  
я его такое начинание поддерживаю  
но вопросы если что ему!

2024-09-11 12:23 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/DiffWidgetService.java
> +    private final ExecutorService executorService = Executors.newFixedThreadPool(3);
и что за это за чертовщина?)  
если ставишь @Autowired, то бин закинь в контекст, а не ручками инициализируй

2024-09-13 17:04 UTC, nekromant322 commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/DiffWidgetTest.java
> +    public void getMonthDiffNoTransactions() {
я бы разбил на несколько тестов, когда чего-то одного нет  
иначе когда сломается не понятно будет шо чинить сразу

2024-09-13 17:06 UTC, AlxndrKatz commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/DiffWidgetTest.java
> +    public void getMonthDiffNoTransactions() {
Принял, сейчас третий сделаю без данных за прошлый год

2024-09-13 17:47 UTC, nekromant322 approved these changes

2024-09-13 19:34 UTC, merged