Изменения в виджете "отношение доходов/расходов к предыдущим сравнимым периодам".
nekromant322/OverMoney pull request #405
Opened 2024-09-17 17:58 UTC by AlxndrKatz

Ранее: выдавалось изменение в % доходов/расходов в сравнении с предыдущим месяцем и одноименным методом предыдущего года (если есть данные за предыдущий год). При этом незавершенный преиод сравнивался с завершенными.

Сейчас: базовым месяцем для сравнения является месяц, предшествующий дате запроса. Данные базового месяца сравниваются с педшествующим месяцем этого же года и с одноименным (с базовым) месяцем предыдущего года - в сентябре 2024 выдается сравнение "август 2024-июль 2024" и "август 2024-август 2023".

2024-09-17 21:43 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/DiffWidgetService.java
> +        int baseMonth = currentDate.getMonthValue() - 1;
Мне страшно за январь

2024-09-17 21:44 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/DiffWidgetService.java
> +        int previousMonth = baseMonth - 1;
а тут даже за февраль

2024-09-17 21:44 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/DiffWidgetService.java
> +        String baseMonthName = currentDate.minusMonths(1)
а тут получается не страшно

2024-09-17 21:45 UTC, nekromant322 requested changes
Разобраться со счетом месяцев

2024-09-18 08:30 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/DiffWidgetService.java
> +        String previousMonthName = baseDate.minusMonths(1)
Как будто из этого можно вычислить previousMonth, а тут дублирование выходит

2024-09-18 08:31 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/DiffWidgetService.java
> +        String previousMonthName = baseDate.minusMonths(1)
А почему тут без танцев с бубном как строкой выше? Ну или скорее почему по-разному имя достается

2024-09-18 08:57 UTC, AlxndrKatz commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/DiffWidgetService.java
> +        String previousMonthName = baseDate.minusMonths(1)
Имя достается идентично - см перенос строки, строка 39.

2024-09-18 14:25 UTC, nekromant322 approved these changes

2024-09-18 14:26 UTC, merged