OV-281: Новая таблица для подсказок
nekromant322/OverMoney pull request #406
Opened 2024-09-23 15:58 UTC by AlxndrKatz

Таблица подсказок, регистрирующая точность подсказок при назначении категорий транзакции. 

Запись подсказок привязана к эндпойнту "/transaction/define" отдельным методом assessAndSaveSuggestion сервиса SuggestionService.

2024-09-23 20:54 UTC, nekromant322 requested changes
Надо бы из таблицы с транзакциями убрать suggestedCategoryId и accuracy  
Более того - хорошо бы не проебать значения которые там уже есть, если по уму  
Нужно миграцию по этому поводу написать  
Ну и естественно в коде который сохраняет в таблицу транзакций - теперь сохранять в новую таблицу

2024-09-29 16:39 UTC, nekromant322 requested changes
Немного порефакторить и все гуд

2024-09-29 16:39 UTC, nekromant322 commented on orchestrator_service/src/main/resources/db/changelog/db.changelog-master.xml
> +    <include file="v1.0.0/021.db-changelog-transactions-drop-suggested-category-and-accuracy.xml" relativeToChangelogFile="true"/>
Если все три добавляются в рамках одного ПРа, мб объединить?

2024-09-29 16:39 UTC, nekromant322 commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/SuggestionServiceTest.java
> +                .algorithm("LEVENSHTEIN")
Думаю стоит завести енам в модуле ДТО с пока-что единственным значением, потом туда добавятся :)

2024-09-29 16:39 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/mapper/TransactionMapper.java
> +    private SuggestionRepository suggestionRepository;
А погнали не будем в мапере логику по походам в бд дергать, все таки это бизнес логика? В метод мапера можно передать сразу объект Suggestion

2024-09-30 06:45 UTC, AlxndrKatz commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
>                  transactionDefineDTO.getCategoryId());
Этот метод не подсчитывает количество транзакций. Он связан с ручным определением категории драг-н-дропом.

2024-09-30 19:42 UTC, nekromant322 requested changes

2024-09-30 19:42 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/SuggestionService.java
> +        Suggestion suggestion = suggestionRepository.findSuggestionByTransaction(transaction);
```suggestion
        Suggestion suggestion = transaction.getSuggestion();
```

2024-09-30 19:42 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/SuggestionService.java
> +    public void editSuggestion(UUID transactionId, Long categoryId) {
название метода не нравится
я по контексту понял что "метод выставляет правильную категорию для подсказки", по названию ваще не понятно

2024-09-30 19:42 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +        suggestionService.editSuggestion(transactionDefineDTO.getTransactionId(), transactionDefineDTO.getCategoryId());
это можно вызвать из DefineService

2024-09-30 19:42 UTC, nekromant322 commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/SuggestionServiceTest.java
> +        suggestionService.editSuggestion(transactionId, categoryId);
тестировать методы по одному

2024-10-01 21:08 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +                        transaction.getSuggestion()))
В таком сетапе уже можно второй параметр и не передавать, получается

2024-10-01 21:08 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/SuggestionService.java
> +        //Suggestion suggestion = suggestionRepository.findSuggestionByTransaction(transaction);
А это тут зачем?

2024-10-02 10:06 UTC, nekromant322 approved these changes

2024-10-02 10:07 UTC, merged