Добавил приоритезацию алгоритмов подбора категории. А также, если оди…
nekromant322/OverMoney pull request #426
Opened 2024-10-16 14:42 UTC by AlexeyVolkovProg

…н падает с ошибкой, работу на себя берет другой

2024-10-16 15:07 UTC, SemionHaritonov commented on dto/src/main/java/com/override/dto/constants/SuggestionAlgorithm.java
> +    public static SuggestionAlgorithm fromName(String name) {
решение с свитч-кейс будет выглядеть страшно при добавлении новых алгоритмов. как насчет чего-то типа? 

`public static SuggestionAlgorithm getByName(String name) {
  return SuggestionAlgorithm.values().stream()
    .filter(фильтрануть по имени алгоритма)
    .findFirst()
    .orElseThrow(выкинуть ошибку)
}`

2024-10-16 15:21 UTC, SemionHaritonov commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +                                     @Value("${recognizer.algorithms}") List<String> algorithms) {
гарантирует ли такое заполнение из конфига очередность, если мы хотим указывать в порядке приоритетов?

2024-10-16 15:30 UTC, SemionHaritonov commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +            CategoryRecognizer recognizer = findRecognizerAlgorithm(algorithm);
тут идет выбор рекогнайзера по алгоритму. правильно ли я понимаю, что одному алгоритму соответствует один рекогнайзер? 

если это так, вероятно стоит объединить конкретный алгоритм алгоритм и конкретный рекогнайзер в каком-нибудь классе или енаме?

2024-10-16 15:40 UTC, SemionHaritonov commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +                                     @Value("${recognizer.algorithms}") List<String> algorithms) {
и я что-то не понимаю, как такой конструктор будет себя вести, если ему попробовать передать коллекцию алгоритмов как аргумент, если он должен прочитать эту коллекцию из файла конфигурации

как минимум если не предполагается передача аргумента, поле надо убрать из аргументов

2024-10-16 18:12 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizer.java
> +    boolean supportsAlgorithm(SuggestionAlgorithm algorithm);
лучше String getAlgorithm()  
тогда не надо будет велосипедирования, просто каждая стратегия будет возращать какой тип она обрабатывает

2024-10-16 18:13 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +                                     @Value("${recognizer.algorithms}") List<String> algorithms) {
стоит использовать @Order, тогда коллекция не важна

2024-10-16 18:18 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +            CategoryRecognizer recognizer = findRecognizerAlgorithm(algorithm);
ага  
стоит просто повесить на рекогнайзеры @ConditionalOnProperty, чтоб они в контекст всасывались только если это в конфиге указано

2024-10-19 13:20 UTC, AlexeyVolkovProg commented on dto/src/main/java/com/override/dto/constants/SuggestionAlgorithm.java
> +    public static SuggestionAlgorithm fromName(String name) {
Дельное замечание, исправил

2024-10-19 13:20 UTC, AlexeyVolkovProg commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +                                     @Value("${recognizer.algorithms}") List<String> algorithms) {
Согласен, @order здесь будет использовать удобнее

2024-10-19 13:20 UTC, AlexeyVolkovProg commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +            CategoryRecognizer recognizer = findRecognizerAlgorithm(algorithm);
Классная аннотация , применил

2024-10-19 13:21 UTC, AlexeyVolkovProg commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +                                     @Value("${recognizer.algorithms}") List<String> algorithms) {
Конструктор пофиксил

2024-10-19 17:23 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +        System.out.println(recognizers.size());
это зачем?

2024-10-19 17:24 UTC, nekromant322 commented on dto/src/main/java/com/override/dto/constants/SuggestionAlgorithm.java
> +    }
А зачем нужен этот метод?

2024-10-21 09:07 UTC, AlexeyVolkovProg commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +     * Список приоритетов алгоритмов можно задать в yml в поле recognizer.algorithms
Понял, забыл комментарий изменить)
Оставляем задание приоритетов через код?
Аннотация order не позволяет брать порядок из application.yml

2024-10-21 09:08 UTC, AlexeyVolkovProg commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +        System.out.println(recognizers.size());
Упс, забыл убрать. Использовал для проверки подгрузки бинов в массив

2024-10-21 11:08 UTC, kovaaf requested changes

2024-10-21 11:08 UTC, kovaaf commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
>          if (recognizerResult != null && recognizerResult.getCategory() != null) {
Повторная проверка, попробуй всё запихнуть перед break

2024-10-21 11:59 UTC, kovaaf approved these changes

2024-10-21 12:00 UTC, merged