Voice message max length configuration
nekromant322/OverMoney pull request #48
Opened 2023-05-18 23:06 UTC by kyomexd

Максимальная длина сообщения в секундах задается в константе в OverMoneyBot

2023-05-19 07:13 UTC, etozhealexis commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/OverMoneyBot.java
> +    private final String TRANSACTION_MESSAGE_INVALID = "Мы не смогли распознать ваше сообщение. " +
как будто бы можно для констант сделать уже отдельный класс

2023-05-19 07:18 UTC, etozhealexis commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/OverMoneyBot.java
> +    private final String TRANSACTION_MESSAGE_INVALID = "Мы не смогли распознать ваше сообщение. " +
(не енам)

2023-05-19 07:21 UTC, etozhealexis requested changes
вынести константы в отдельный класс а-ля MessageConstants

2023-05-19 08:25 UTC, etozhealexis approved these changes

2023-05-19 19:23 UTC, nekromant322 commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/OverMoneyBot.java
> +    private final int VOICE_MESSAGE_MAX_LENGTH = 10;
а всмысле не из .yml?

2023-05-20 09:58 UTC, nekromant322 commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/OverMoneyBot.java
> +            }
а эта логика точно тут должно быть?  
может тут просто вызвать сервис и туда все это добро спрятать

2023-05-20 17:51 UTC, nekromant322 approved these changes

2023-05-20 17:51 UTC, merged