Admin page w/ limited access and announce function added
nekromant322/OverMoney pull request #53
Opened 2023-05-20 22:46 UTC by kyomexd

Добавил страницу /admin/panel, доступ к ней ограничен дополнительным фильтром (проверяет на совпадение юзернейма из конфига)

Текст анонса задается на странице, после с набором всех айдишников юзеров отправляется в телеграм-бот-сервис, где происходит рассылка

2023-05-20 23:09 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/model/AnnounceDTO.java
> +}
перенести в dto

2023-05-20 23:12 UTC, etozhealexis commented on orchestrator_service/src/main/resources/application.yml
> +    allowed_users: Marandyuk_Anatolii, HomerTheBald, kyomexd, etozhealexis, NikitaAkimovv
сделай так
- Marandyuk_Anatolii
- HomerTheBald
- kyomexd
- etozhealexis
- NikitaAkimovv

2023-05-20 23:12 UTC, etozhealexis commented on orchestrator_service/src/main/resources/application.yml
> +    allowed_users: Marandyuk_Anatolii, HomerTheBald, kyomexd, etozhealexis, NikitaAkimovv
вместо точек минусы, у гита автозамена

2023-05-20 23:14 UTC, etozhealexis commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/model/AnnounceDTO.java
> +}
то же, что и в оркестраторе

2023-05-20 23:16 UTC, etozhealexis requested changes
чутка порефакторить

2023-05-21 01:52 UTC, nekromant322 requested changes
Обработку ошибок доьавить и немног рест стиля

2023-05-21 01:52 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/config/filter/AdminPageFilter.java
> +        return !path.equals(ADMIN_PANEL_PATH) && !path.equals(SEND_ANNOUNCE_PATH);
Я бы пути сделал ака /admin/** и тут бы не equals бахал, а startsWith

2023-05-21 01:52 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/config/filter/AdminPageFilter.java
> +    private final String SEND_ANNOUNCE_PATH = "/announce/send";
/announce мб тоже админским ?

2023-05-21 01:52 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/AnnounceController.java
> +    @PostMapping("/send")
Почему не просто Post_/announce ?

2023-05-21 01:52 UTC, nekromant322 commented on telegram_bot_service/src/main/java/com/overmoney/telegram_bot_service/service/AnnounceService.java
> +    }
А если один из юзеров заьанил бота ? Эксепшон по зубам прилетит и всем остальным анонс не дойдет -_-

2023-05-21 17:54 UTC, etozhealexis approved these changes

2023-05-21 17:58 UTC, nekromant322 approved these changes

2023-05-21 17:58 UTC, merged