Added method for get Accounts id with recent activity
nekromant322/OverMoney pull request #73
Opened 2023-05-29 12:30 UTC by NikitosikQQ

Добавлен метод, который возвращает id аккаунтов из БД, имеющих недавно заведенные транзацкии.
"Недавность" зависит от новой переменной в app.yaml recent-activity:activityDays.

2023-05-29 12:42 UTC, etozhealexis submitted a review, later dismissed

2023-05-29 13:11 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/TransactionRepository.java
> +    List<Long> findActiveAccounts(@Param("minimalDate") LocalDateTime minimalDate);
рассылку хотелось бы по пользователям, а не по чатикам  
ну типо в лс

2023-05-30 17:14 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/OverMoneyAccountService.java
> +                (transactionRepository.findActiveAccounts(minimalDate));
`transactionRepository.findActiveAccounts  `
это даже звучит нелогично  
мб в `accountRepository`?  
Зачем делать два запроса и между ними данные в лист класть, есть можно сделать один запрос, который сделает все сразу?

2023-05-30 17:15 UTC, nekromant322 requested changes
нужен рефакторинг по части работы с бд

2023-05-31 15:36 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/OverMoneyAccountService.java
> +    private TransactionRepository transactionRepository;
не используешь

2023-05-31 17:33 UTC, nekromant322 approved these changes

2023-05-31 17:34 UTC, merged