Added functional to edit category
nekromant322/OverMoney pull request #86
Opened 2023-06-05 19:00 UTC by NikitosikQQ

-Добавлен фунционал для редактирования категорий в модальном окне
-Добавлена возможность удалить ключевые слова из категории в модальном окне
-Изменен стиль модального окна категории

2023-06-06 16:53 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/CategoryController.java
>      }
блин, че то не здорово все это выглядит, я эту фичу пропустил не сильно посмотрев  
Как на счет того чтоб передавать джейсонку с двумя айдишниками? тут черт ногу сломит в таком апи, в бади число, в path variable еще одно число

2023-06-06 16:55 UTC, nekromant322 requested changes
немного рефакторинга для merge  
и кстати ендпоинт я бы назвал /category/merge  
да, я знаю что глагол а не существительное, но кто черт подери этот merger

2023-06-06 23:32 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/CategoryController.java
>          return ResponseEntity.ok(HttpStatus.ACCEPTED);
При работе с сервисами могут возникать исключения, я бы их обрабатывал с отсылкой назад соответствующего статуса http;

При посте и при удалении должен возвращаться один и тот же статус? 
Аналогично при посте и путе. Казалось, есть какие-то свои коды для успешных обновления и удаления.

2023-06-06 23:34 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/mapper/CategoryMapper.java
> +    private List<KeywordIdDTO> getCategoryKeywords(Category category) {
как будто тут можно передать не категорию, а Id аккаунта, чтобы искать сразу в базе ключевых слов

2023-06-06 23:36 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/KeywordRepository.java
> +    void deleteByKeywordId(KeywordId keywordId);
(вопрос для обсуждения)
думаю, лучше делать так, чтобы всякие методы удаления/создания возвращали не войд, а то, над чем они работали. сложилось такое мнение после написания тестов, мол так проще отследить.

2023-06-06 23:38 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/service/CategoryService.java
> +        Category updatedCategory = categoryMapper.mapCategoryDTOToCategory(categoryDTO, account);
почему один сеттер зашит в маппере, а другой навызывается в этом методе с обращением второй раз к categoryDTO?

2023-06-06 23:43 UTC, VladimirBalakin commented on orchestrator_service/src/test/java/com/override/orchestrator_service/service/CategoryServiceTest.java
> +        keywordId.setAccountId(123l);
малая эль и единица выглядят похоже, смущает

2023-06-06 23:46 UTC, VladimirBalakin reviewed
плохого не нашел

2023-06-06 23:50 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/CategoryController.java
>          return ResponseEntity.ok(HttpStatus.ACCEPTED);
Я гуглил насчет удаления, советовали данный код для успешного ответа.

Если исключение в моменте работы возникает, передается 500 ошибка, по крайней мере в консоли на фронте я ее ловлю спокойно

2023-06-06 23:52 UTC, NikitosikQQ commented on orchestrator_service/src/main/java/com/override/orchestrator_service/mapper/CategoryMapper.java
> +    private List<KeywordIdDTO> getCategoryKeywords(Category category) {
Это нужно для отображения на фронте ключевых слов конкретной категории, а не аккаунта

2023-06-07 05:15 UTC, etozhealexis commented on orchestrator_service/src/main/resources/static/scripts/overview_scripts.js
>      let categorySpace = document.querySelector('.categories-space');
Да-да, комментарий по жаваскрипту
Константы наверное лучше вынести из функции, чтоб были глобальной переменной

2023-06-07 14:30 UTC, etozhealexis approved these changes
Остальное успел прокомментировать  Владимир, больше нареканий нет

2023-06-07 15:10 UTC, merged