Просмотр всех транзакций на отдельной странице
nekromant322/OverMoney pull request #87
Opened 2023-06-06 14:18 UTC by etozhealexis

Добавил страницу по адресу /transaction, на которой отображаются все транзакции аккаунта в формате "Категория | Сумма | Примечание | Дата", отображаются последние 50 транзакций. Чтобы увидеть более старые транзакции необходимо проскроллить страницу. Список изменений:
- создал страничку transaction.html
- создал скрипты для странички (transaction_scripts.js)
- добавил TransactionPageController
- добавил метод получения истории транзакций в TransactionController
- добавил метод для получения истории транзакций в TransactionService
- написал SQL-запрос в TransactionRepository, с помощью которого можно получить историю транзакций
- обновил TransactionDTO (добавил имя категории транзакции)
- обновил маппинг Transaction в TransactionDTO
- обновил тест в TransactionMapperTest
- добавил тест в TransactionServiceTest

2023-06-06 16:40 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/TransactionPageController.java
> +    @GetMapping("/transaction")
множественное число у конечной точки

2023-06-06 16:48 UTC, VladimirBalakin commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +                transactionService.findTransactionsLimitedByUserId(telegramUtils.getTelegramId(principal), limit, start);
лимитед бай юзер ид звучит так, будто выдача ограничена ид

2023-06-06 16:59 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/TransactionPageController.java
> +    @GetMapping("/transaction")
предлагаю ендпоинт назвать тупо /history

2023-06-06 17:00 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/mapper/TransactionMapper.java
> +            return TransactionDTO.builder()
так там же билдер, так что не одинаковые действия. Или ты предлагаешь set'ом дописать?

2023-06-06 17:02 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +    @GetMapping("/transaction/history")
какого черта тут /history?  
это же логично просто GET_/transactions рестовый метод  
по условию задачи страница должна быть доступна по /transaction/history  
а ваще мне чет охота чтоб страница была просто /history

2023-06-06 17:02 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/TransactionPageController.java
> +    @GetMapping("/transaction")
в задании было "/transaction"

можно, но как будто бы в контроллере этом больше ничего не планируется

2023-06-06 17:03 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/TransactionPageController.java
> +    @GetMapping("/transaction")
не стоит отдельного контроллера   
погнали в MainPageController запихнем  
заодно можно назвать его ViewController, и просто мапинги урла на html файлик там по сути рисовать

2023-06-06 17:03 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/repository/TransactionRepository.java
> +    List<Transaction> findTransactionsLimited(@Param("id") Long id, @Param("limit") Integer limit, @Param("start") Integer start);
PagingAndSortingRespoitory шутка для тебя?)

2023-06-06 17:04 UTC, nekromant322 requested changes
уйти от нативного sql, data jpa уже изобрели все велосипеды за нас

2023-06-07 11:31 UTC, NikitosikQQ commented on orchestrator_service/src/main/resources/static/scripts/transaction_scripts.js
> +})
Раз мы иногда оставляем комментарии по js, то может вынести запрос в отдельный метод? А то он повторяется, отличаясь лишь одной строчкой. Думаю можно как то под один метод все скомпоновать

2023-06-07 16:46 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/HistoryController.java
> +                .map(transaction -> transactionMapper.mapTransactionToDTO(transaction))
ну шо за херота  
есть же /transactions  
почему бы оттуда транзакции не доставать?  
TransactionRestController который

2023-06-07 16:46 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/HistoryController.java
> +                .map(transaction -> transactionMapper.mapTransactionToDTO(transaction))
я уж молчу про обилие логики в контроллерах

2023-06-07 16:47 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/HistoryController.java
> +                .map(transaction -> transactionMapper.mapTransactionToDTO(transaction))
потому что они там сортируются по дате не в ту сторону

2023-06-07 16:48 UTC, etozhealexis commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/HistoryController.java
> +                .map(transaction -> transactionMapper.mapTransactionToDTO(transaction))
и там метод другой используется для получения транзакций

2023-06-07 16:49 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/HistoryController.java
> +                .map(transaction -> transactionMapper.mapTransactionToDTO(transaction))
это функционал связанный с транзакциями же?

2023-06-07 16:51 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/HistoryController.java
> +                .map(transaction -> transactionMapper.mapTransactionToDTO(transaction))
для примера: есть сущность `User `с полем `gender`  
Если стоит задача реализовать апи которое бы возвращало мужчин, и отлдельно возвращало бы женщин  
Ты предлагаегт ManRestController и WomanRestController создавать?

2023-06-08 16:14 UTC, nekromant322 approved these changes

2023-06-08 16:15 UTC, merged