Добавление страницы с аналитикой транзакций
nekromant322/OverMoney pull request #92
Opened 2023-06-08 12:38 UTC by NikitosikQQ

- Добавлена новая стр по /analytics с отрисовкой круговой диаграммы с транзакциями по категориям, разделяя доходы и расходы

2023-06-08 14:00 UTC, etozhealexis submitted a review, later dismissed

2023-06-08 20:43 UTC, nekromant322 commented on orchestrator_service/pom.xml
> +        </dependency>
а это зачем?

2023-06-08 20:44 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/ViewController.java
> +    }
почему тут снова Лехины чейнджы?

2023-06-08 20:46 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/AnalyticsController.java
> +    }
есть мнение, что тут в будущем будет куча разных "аналитических" ендпоинтов с данными в разных разрезах  
Я бы, наплевав на всякие бест практисы рестовые понятно обозвал это добро типо `/totalCategorySums/{type}`

2023-06-09 13:48 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/AnalyticsController.java
> +    public List<AnalyticsDataDTO> getAnalyticsData(Principal principal, @PathVariable("type") Type type) throws InstanceNotFoundException {
имя метода тоже могло бы суть отображать в качестве мини документации

2023-06-09 13:49 UTC, nekromant322 commented on orchestrator_service/src/main/java/com/override/orchestrator_service/controller/rest/TransactionController.java
> +    }
а этот метод зачем, если для аналитики "отдельное" апи?

2023-06-09 13:51 UTC, nekromant322 requested changes
попробовать считать суммы в бд оптом

2023-06-09 16:46 UTC, nekromant322 approved these changes

2023-06-09 16:47 UTC, merged