API recognizer для неточного поиска
nekromant322/OverMoney pull request #95
Opened 2023-06-09 17:48 UTC by VladimirBalakin

2023-06-09 18:12 UTC, nekromant322 commented on recognizer_service/src/main/java/com/override/recognizer_service/controller/rest/RecognizerController.java
> +    public CategoryDTO processVoiceMessage( @RequestParam(name = "message") String message,
```suggestion
    public CategoryDTO processVoiceMessage(@RequestParam(name = "message") String message,
```

2023-06-10 15:49 UTC, nekromant322 commented on recognizer_service/src/test/java/com/override/recognizer_service/CategoryRecognizerServiceTests.java
> +                        .recognizeCategory(message, List.of(categoryWithLupa,categoryWithPupa)).getName(),
```suggestion
                        .recognizeCategory(message, List.of(categoryWithLupa, categoryWithPupa)).getName(),
```

2023-06-10 15:49 UTC, VladimirBalakin commented on recognizer_service/src/main/java/com/override/recognizer_service/controller/rest/RecognizerController.java
> +    public CategoryDTO processVoiceMessage( @RequestParam(name = "message") String message,
убрал

2023-06-10 15:49 UTC, nekromant322 commented on recognizer_service/src/test/java/com/override/recognizer_service/CategoryRecognizerServiceTests.java
> +                        .recognizeCategory(message, List.of(categoryWithBeer,categoryWithBlank)).getName(),
```suggestion
                        .recognizeCategory(message, List.of(categoryWithBeer, categoryWithBlank)).getName(),
```

2023-06-10 15:52 UTC, nekromant322 requested changes
подлечить стиль

2023-06-10 17:27 UTC, NikitosikQQ commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +            return ((maxLength - LevenshteinDistance.getDefaultInstance().apply(strOne, strTwo)) / maxLength);
как будто тут лишние скобочки)) Доебаться так по полной

2023-06-10 18:04 UTC, VladimirBalakin commented on recognizer_service/src/main/java/com/override/recognizer_service/service/CategoryRecognizerService.java
> +            return ((maxLength - LevenshteinDistance.getDefaultInstance().apply(strOne, strTwo)) / maxLength);
убрал

2023-06-11 10:22 UTC, nekromant322 submitted a review, later dismissed

2023-06-11 10:40 UTC, etozhealexis commented on recognizer_service/src/main/java/com/override/recognizer_service/controller/rest/RecognizerController.java
> +    }
я так и не понял, почем processVoiceMessage, если засылается текст, то есть мы можеи распознать любое сообщение так, не?

2023-06-11 10:44 UTC, VladimirBalakin commented on recognizer_service/src/main/java/com/override/recognizer_service/controller/rest/RecognizerController.java
> +    }
потому тчо невнимательно накопипастил

2023-06-11 11:40 UTC, etozhealexis approved these changes

2023-06-11 11:41 UTC, merged